---
- hosts: all
  user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
  vars_files:
    - vars/defaults.yml

  roles:
    - webserver
    - database
    - sidekiq
