- name: Install nginx
  apt: pkg=nginx state=latest

- name: Remove the default app
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/default"

- name: Remove the app's config, if exists
  file:
    state: absent
    path: "/etc/nginx/sites-available/default"

- name: Remove the app's symlink, if exists
  file:
    state: absent
    path: "/etc/nginx/sites-enabled/{{ app_name }}"

- name: Configure nginx for the app
  template: src=etc_nginx_sites-available.conf.j2 dest=/etc/nginx/sites-available/{{ app_name }} group=www-data owner=www-data force=yes

- name: Enable the app
  file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link

- name: Restart nginx
  service:
    name: nginx
    state: restarted
